### ISSUE TITLE
Setting the permutation iteration?

### ISSUE THREAD

**Issue by polarathene** [mmstick/permutate#2]
I was referred to your crate for handling permutations but have been told if I want the 36th permutation for example, the iterator would likely calculate every permutation up until that point? Would it be possible to support avoiding that? 

Use case is for permutating long strings with various rules, if I calculate the first 10 trillion permutations and terminate the program, as long as I had the current iteration number it should be possible to provide that to resume progress on my permutations when running the program again and providing the iteration number? It would be nice not to do all that processing if it can be avoided :)

Example of how I'd assume it might be approached. A string with the length of 3 where the first two elements are `"a" ... "z"` and the third `0 ... 9`. I'd have `aa0`, `aa1` and so forth, if I wanted the 36th permutation it'd would probably do something like:

```Rust
// Gets the individual index per permutation char representing a string
fn permutation_index(element_sizes:Vec<u32>, index:u32) -> Vec<usize> {
    let mut r = element_sizes.iter().rev().scan(index, |x, y|
        if *x == 0 { None } else {
            let (div, rem) = (*x / y, *x % y);
            *x = div;
            Some(rem as usize)
        }
    ).collect::<Vec<usize>>();
    // flip the order back to the original direction
    r.reverse();
    r
}


fn main() {
    // [a...z, a...z, 0...9], [0, 0, 0] == "aa0", [0, 0, 1] == "aa1"
    let element_sizes = vec![26, 26, 10];
    let nth_permutation = 36;
    
    let index = permutation_index(element_sizes, nth_permutation);
    
    // [3, 6] "ad6"
    println!("done {:?}", index);
}

```

Some users on IRC suggested:
> This crate could benefit from specializing  `Iterator::nth()`.

> You could add a #[derive(serialize, deserialze)] on your Iterator, save it and open it whenever you need

---

Technically for my case, it might make more sense to just provide the iteration value such as "ad6" or it's index [3, 6] or [0, 3, 6] depending on what works better for your crate.

**Comment by mmstick** [comment]
I can look into specializing the `nth()` method. The main cost of using `next()` or `next_with_buffer(&mut buffer)` is just that it returns the result of each iteration. It will always have to compute the permutation though. I can also supply a `get_index()`, `set_index()`, and `from_index()` method if you want that.

**Comment by polarathene** [comment]
I haven't looked into how the permutations were being done, I figured based on how the data is laid out when providing it to the permutate method that it'd just be iterating through indexs similar to how I showed above which shows how permutations could avoid computing prior ones.

For me personally the methods would not be of use if I can't skip computation time to begin permutations from a given permutation index/value.I don't know how iterators work but I guess you can't serialize/deserialize the progress like someone suggested?

**Comment by mmstick** [comment]
To make a structure able to iterate, all you need to do is define the `next()` method. Each call to `next()` in the `Permutate` structure just increments an internal `Counter` field, which is just a list of indexes that are incremented for each iteration. When an individual index value has been incremented past it's max value, the next index value is incremented and that index value is reset to 0. The state of that `Counter` determines the indexes to use in creating the permutation.

What you're asking for is the ability to modify that `Counter` directly. That can be done with the methods I described above. I could create a `Permuate::from_index()` function to create a new permutator with a predefined state. I could also provide you with a `permutator.get_index()` method to get a copy of the internal counter, and a `permutator.set_index()` to set a new state.

**Comment by polarathene** [comment]
Perhaps I misunderstood when you said this:

>  It will always have to compute the permutation though.

So with the new methods if I used `permutator.set_index(36)` would it need to compute 36 permutations or just the 36th?

**Comment by mmstick** [comment]
I'm still figuring out which sort of API I will expose. At the moment, I am thinking of requiring that you specify both the iteration number and the index counters when using the setter, while the getter will get you those values for the current permutation. That would look more like:

```rust
permutator.set_index(vec![1, 4, 2, 0], 36);
let permutation = permutator.next(); // Get the 36th value
let (current_iteration, indexes) =  @permutator.get_index(); // get values for the 36th iteration
```

The purpose of also supplying the iteration number along with the indexes is because the iterator is designed to stop iterating once it is determined that it has already supplied all possible values. Otherwise, the incrementer for the counters would cause the iterator to loop forever.

**Comment by mmstick** [comment]
Pushed a new version ( https://github.com/mmstick/permutate/commit/a907d876637f4e1b120388ac40edecb276eed3b8 ). Documentation should be generated shortly. The `nth()` method was specialized, and a new `get_index` and `set_index` method was added. Documentation has also been improved.

**Comment by mmstick** [comment]
New documentation: https://docs.rs/permutate/0.3.0/permutate/

**Comment by polarathene** [comment]
@mmstick I thouoght that with the method I supplied earlier the 36 value could with the known amount of elements/length for each character being generated in the string, produce that index that you're supplying with `set_index()`? Assuming that for `"aa0"` to `"zz9"` would mean the index `"ad6"` was [0, 3, 6]?

I'm trying to get better permutation generation performance by creating permutations in rust instead of relying on an external program to pipe in it's strings and read from stdin. Unfortunately it seems to be much slower the way I'm doing it, could you advise? I'm not sure if the approach I'm using can use `next_with_buffer()`, I would like to be able to take x amount.

[Rust Playground](https://is.gd/6SIzLj). So far I've been advised to skip the collects and that currently alot of allocations and re-allocations are happening. Is what I'm trying to do possible to get near hashcat or even maskprocessor speeds?

**Comment by mmstick** [comment]
You may use `next_with_buffer`, but the particular issue is that you are using this with characters instead of strings. You also don't need to use `into_iter` because `Permutator` is already an iterator. You're paying a high price, as a result. You would need to use a value-based permutator rather than a reference-based permutator.

**Comment by polarathene** [comment]
Another suggestion was to utilize permutate with something like Rayon which would probably help quite a bit too I guess? With this new indexing feature I suppose I can compute the total amount of permutations and divide by how many threads to split the workload to setting the index for each other permutator :) already a good use for this feature!

**Comment by polarathene** [comment]
I'm still new to Rust, some help on optimizing what I'm trying to do is being given on #rust-beginners IRC channel. If it's not too much trouble for showing how you'd better handle the generation of strings from character sets("a..."z" "0"..."9") etc that would be appreciated :)

I got the impression from the docs that it expected `&[&[&_]]`, are you saying that your permutation crate is not ideal for high speed permutation generation?(as in it's only able to do the reference-based kind?)

**Comment by mmstick** [comment]
I've implemented a second permutation structure which permutates with values that implement `Copy`. This is much more suitable for what you are trying to do, as bytes are cheaper to copy than to reference. This crate was designed to permutate strings, rather than bytes/characters, which are cheaper to reference than to copy.

This is how you would implement what you are looking for, which generates a vector of all possible combinations for 5 characters:

```rust
extern crate permutate;
use permutate::ValuePermutator;
use std::io::{self, Write};
use std::iter;

const KEYS: &'static [u8] = b"abcdefghijklmnopqrstuvwxyz0123456789";

fn main() {
    let stdout = io::stdout();
    let mut stdout = stdout.lock();
    let keys = iter::repeat(KEYS).take(5).collect::<Vec<&'static [u8]>>();
    let mut permutator = ValuePermutator::new(&keys);

    let mut outputs: Vec<String> = Vec::with_capacity(permutator.max_permutations());
    if let Some(mut permutation) = permutator.next() {
        // let _ = stdout.write(&permutation);
        outputs.push(unsafe { String::from_utf8_unchecked(permutation.clone()) });
        while permutator.next_with_buffer(&mut permutation) {
            // let _ = stdout.write(&permutation);
            outputs.push(unsafe { String::from_utf8_unchecked(permutation.clone()) });
        }
    }
}
```
When writing outputs directly to /dev/null on my laptop, this takes 2 seconds.

**Comment by polarathene** [comment]
> When writing outputs directly to /dev/null on my laptop, this takes 2 seconds.

When I tried this without any printing to stdout I got a result of 83 seconds or without numbers 16-17 seconds, and then I wondered how you got such better results on a laptop....derp I've been comparing Rust's debug perf..whoops. 

2.622 seconds on release with i5-6500(stdout commented out). Little bit longer(stdout uncommented) with output to /dev/null if I did this right:
```
time cargo run --release > /dev/null 2>&1
cargo run --release > /dev/null 2>&1  3.29s user 0.17s system 98% cpu 3.517 total
```

---

When using your example snippet, it does fail to compile with the following error:
```
error[E0432]: unresolved import `permutate::ValuePermutator`
use permutate::ValuePermutator;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^ Did you mean `self::permutate`?
```

If I remove that and change the call to:
```
let mut permutator = permutate::ValuePermutator::new(&keys);
```

It works fine. Much faster than the `maskprocessor` tool I was using before, thanks for the awesome crate and support! :) The example would possible be useful in docs or as a crate example that I've seen some repos package(I think cargo has a way to run them?). 

If you do such, pointing out the example and the cargo command to run it in the repo Readme and main Docs.rs page would be super useful, your docs are already better than most I've come across so far for crates, especially with the examples you've included(and the stdout tip vs println).

**Comment by mmstick** [comment]
You wouldn't believe how many performance issues that are reported against Rust, and are solved by reminding to benchmark release builds rather than debug builds. There's likely a handful of things we can do to make performance even better for your use case though. The implementation of this crate is very simplistic / little effort placed into optimizations.

I could integrate `SmallVec` so that heap allocated-vectors are reduced, and once the `conservative_impl_trait` is stabilized, it might be possible to return an `impl Iterator<Item = T>` type instead of a `Vec<T>` type with the `next()` method. Would be a breaking change for that last one though.

**Comment by polarathene** [comment]
Your crate works very well already :) I was using stdout to compare against a similar program. It seems like it'd be fast enough for using in my program(0.5 seconds on 26^5 permutations).

I get 15 seconds printing each string out with stdout and an extra stdout call with "`b\n"`, without the \n it goes down to about 2.7 secs. The similar program is managing 13-15 seconds and it seems the `\n` triggering new lines/flushes is the cause for perf hit, the extra second or two the other program achieves I think must be due to C vs Rust?

---

I don't think I'll run into this any time soon, but a large permutation set could cause an overflow for max_permutations? 95^10 for example, I'm not sure what would happen if someone tried something of that size.

**Comment by mmstick** [comment]
When writing newlines to stdout, it's important that you use a [BufWriter](https://doc.rust-lang.org/std/io/struct.BufWriter.html) to buffer your writes.

```rust
use std::io::{self, Write, BufWriter};

fn main() {
    let stdout = io::stdout();
    let mut stdout = BufWriter::new(stdout.lock());
}
```

Then you can write to `BufWriter` as before, and not trigger the flushes when a newline is encountered. It will only flush when you call `flush()`, the `BufWriter` is dropped, or the max buffer capacity has been reached (default is 8K).

As for integer overflows, integer overflows in Rust cause a panic, so in the event that someone attempts that, their program will just crash with an integer overflow panic. Overflowing is only allowed when you call a method like `wrapping_add()` or `wrapping_sub()`.
